### ISSUE TITLE
Add a goal to update the versions listed as properties in a given parent pom

### ISSUE THREAD

**Issue by dscho** [scijava/scijava-maven-plugin#1]
We used to call a helper script called [bump-pom-scijava.sh](https://github.com/scijava/scijava-scripts/blob/master/bump-pom-scijava.sh) to update the versions in `pom-scijava`. This was a bit fragile, and we can do much better than that if we use full-blown Java instead of hacky shell scripting.

The logical place for the code to do the job is the `scijava-maven-plugin`.

**Comment by ctrueden** [comment]
The versions-maven-plugin can be used to report which plugins and/or dependencies have newer versions, via the `versions:display-plugin-updates` and `versions:display-dependency-updates`, respectively. (Passing `-U` with them seems to work more reliably, in my experience.)

We do not always want to bump all versions to the latest; the point of pom-scijava is to ensure all the versions are _compatible_, not _latest_. We now have status.scijava.org to fully report on the situation, including which dependencies could be bumped, and which ones could use a new release based on their SNAPSHOT status.

As such, we no longer need to make any improvements to scijava-maven-plugin along these lines.
