### ISSUE TITLE
Consider a copy goal

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-maven-plugin#11]
We should investigate whether a copy goal would be necessary. The question is if `maven-resources-plugin:copy-resources` is sufficient.

See [SO post](http://stackoverflow.com/questions/586202/best-practices-for-copying-files-with-maven).

**Comment by ctrueden** [comment]
There is also `dependency:copy`. But actually, what I meant in [my email](https://groups.google.com/d/msg/fiji-devel/_c8-aL_eK24/ZPRmU8Yql5kJ) was actually an improvement to the [imagej-maven-plugin](https://github.com/imagej/imagej-maven-plugin) to specifically support copying "bare" resources (e.g., scripts and configuration files) into a desired place in an ImageJ directory structure. We could use the convention of `src/main/imagej` for this, which the plugin would pick up on and copy appropriately. Such a feature would be necessary to make the [fiji.git build](https://github.com/fiji/fiji) _fully_ replicate a Fiji user installation from scratch.

**Comment by ctrueden** [comment]
OK, I should file a separate issue for the `imagej-maven-plugin` level resources thing.

**Comment by ctrueden** [comment]
Upon consideration, let's close this in favor of imagej/imagej-maven-plugin#11. I do not think we need a general-purpose scijava:copy goal; we can reopen later if we find a use case for it beyond the imagej-maven-plugin use case.
