### ISSUE TITLE
Allow overriding of "jars" and "plugins" location

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava-maven-plugin#18]
Currently, you can set `scijava.app.directory`, which is the path to the base directory of the SciJava application. And you can set `scijava.app.subDirectory`, which is the relative path to a subdirectory beneath `jars` or `plugins` inside the SciJava application folder structure. But there is no way (AFAICT) to override the `copy-jars` mojo's assumption to copy artifacts into the `jars` folder (or `plugins` folder in the case of ImageJ 1.x plugins).

I propose a new property that defines this value. Then all the legacy ImageJ 1.x plugins in Fiji can override this property with `plugins` instead of `jars`, and we can get rid of the hacky ImageJ1 and Bio-Formats hardcoded code blocks, in favor of declarative POM goodness.

**Comment by stelfrich** [comment]
> And you can set `scijava.app.subDirectory`, which is the relative path to a subdirectory beneath jars or plugins inside the SciJava application folder structure.

`scijava.app.subdirectory` is assumed to be relative to `scijava.app.directory`: https://github.com/scijava/scijava-maven-plugin/blob/master/src/it/copy-to-subdirectory/pom.xml#L51

> Then all the legacy ImageJ 1.x plugins in Fiji can override this property with plugins instead of jars, and we can get rid of the hacky ImageJ1 and Bio-Formats hardcoded code blocks, in favor of declarative POM goodness.

With #20 this will even work for dependencies of the project you are installing.

**Comment by ctrueden** [comment]
I finally merged #20, so I guess we can close this issue as fixed. Thanks @stelfrich.
