### ISSUE TITLE
Add flag to fail copy-jars when trying to override artifact with incompatible version 

### ISSUE THREAD

**Issue by stelfrich** [scijava/scijava-maven-plugin#22]
Add a `scijava.failOnIncompatibleVersion` flag that is `false` per default so that `copy-jars` fails if `scijava.failOnIncompatibleVersion==true` and an incompatible version of an artifact is detected.

In any case, a warning should be logged when overriding an artifact with an incompatible version according to SemVer.

**Comment by ctrueden** [comment]
The warning about incompatible versions according to SemVer was implemented quite some time ago!
