### ISSUE TITLE
Flesh out includes/excludes groupIds of SnapshotChecker

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-maven-plugin#8]
Currently the `SnapshotChecker` takes a list of groupIds. This list is basically saying "discovered errors are only valid if they occur in this groupId".

Another option we might want is the ability to say "only consider these groupIds in the recursive search if they are part of this list"

In either or both of these cases, it could make sense to structure them in the more typical Maven `include` and `exclude` blocks.

**Comment by dhoffer** [comment]
I really would like the option to specify groupIds to exclude, I would not want to have to specify groupIds to include unless it supports wildcards.  We have a lot of groupIds...it is not practical to have to specify them individually, plus we want new groupIds to be included by default else it defeats the purpose of this plugin.

**Comment by ctrueden** [comment]
@dhoffer Agreed that full support for GA includes/excludes, including wildcards like other Maven plugins, would be ideal. It is unlikely that @hinerm or I will have time to work on this before the fall though, so if you need it urgently please feel welcome to submit a PR.
